import type { Metadata } from 'next'
import { buildAlternates } from '@/lib/hreflang'
import Breadcrumbs from '@/components/layout/Breadcrumbs'

type Props = { params: Promise<{ locale: string }> }

const CONTENT = {
  fr: {
    title: 'Support',
    description: 'Centre d\'aide NovaDuel. Trouvez des réponses à vos questions.',
    intro: 'Comment pouvons-nous vous aider ?',
    faqs: [
      { q: 'Comment comparer deux joueurs ?', a: 'Rendez-vous sur la page Comparer, recherchez deux joueurs et lancez la comparaison. L\'analyse IA est générée automatiquement.' },
      { q: 'Les données sont-elles à jour ?', a: 'Les statistiques sont synchronisées chaque nuit depuis API-Football pour les 9 ligues majeures.' },
      { q: 'Comment fonctionne l\'analyse IA ?', a: 'Les analyses sont générées par Claude (Anthropic) à partir des statistiques de la saison en cours. Elles sont mises en cache et régénérées périodiquement.' },
      { q: 'Pourquoi un joueur est-il absent ?', a: 'Seuls les joueurs des 9 ligues synchronisées sont disponibles : Premier League, Ligue 1, La Liga, Serie A, Bundesliga, MLS, Saudi Pro League, Champions League, Europa League.' },
    ],
    contact: 'Autre question ? Contactez-nous',
  },
  en: {
    title: 'Support',
    description: 'NovaDuel Help Center. Find answers to your questions.',
    intro: 'How can we help you?',
    faqs: [
      { q: 'How do I compare two players?', a: 'Go to the Compare page, search for two players and start the comparison. The AI analysis is generated automatically.' },
      { q: 'Are the data up to date?', a: 'Statistics are synchronized every night from API-Football for the 9 major leagues.' },
      { q: 'How does AI analysis work?', a: 'Analyses are generated by Claude (Anthropic) based on current season statistics. They are cached and periodically regenerated.' },
      { q: 'Why is a player missing?', a: 'Only players from the 9 synchronized leagues are available: Premier League, Ligue 1, La Liga, Serie A, Bundesliga, MLS, Saudi Pro League, Champions League, Europa League.' },
    ],
    contact: 'Another question? Contact us',
  },
  es: {
    title: 'Soporte',
    description: 'Centro de ayuda NovaDuel. Encuentra respuestas a tus preguntas.',
    intro: '¿Cómo podemos ayudarte?',
    faqs: [
      { q: '¿Cómo comparar dos jugadores?', a: 'Ve a la página Comparar, busca dos jugadores y comienza la comparación. El análisis IA se genera automáticamente.' },
      { q: '¿Los datos están actualizados?', a: 'Las estadísticas se sincronizan cada noche desde API-Football para las 9 ligas principales.' },
      { q: '¿Cómo funciona el análisis IA?', a: 'Los análisis son generados por Claude (Anthropic) basándose en las estadísticas de la temporada actual.' },
      { q: '¿Por qué falta un jugador?', a: 'Solo están disponibles los jugadores de las 9 ligas sincronizadas: Premier League, Ligue 1, La Liga, Serie A, Bundesliga, MLS, Saudi Pro League, Champions League, Europa League.' },
    ],
    contact: '¿Otra pregunta? Contáctanos',
  },
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params
  const c = CONTENT[locale as keyof typeof CONTENT] ?? CONTENT.en
  return {
    title: c.title,
    description: c.description,
    alternates: buildAlternates('/support', locale),
  }
}

export default async function SupportPage({ params }: Props) {
  const { locale } = await params
  const c = CONTENT[locale as keyof typeof CONTENT] ?? CONTENT.en

  return (
    <div className="bg-white min-h-screen">
      <div className="max-w-3xl mx-auto px-6 py-12 md:py-20">
        <Breadcrumbs locale={locale} items={[{ label: 'NovaDuel', href: '/' }, { label: c.title }]} />
        <header className="mt-8 mb-12">
          <h1 className="font-hl font-black text-4xl md:text-5xl text-slate-900 tracking-tighter uppercase mb-4">{c.title}</h1>
          <p className="text-lg text-slate-500 font-medium">{c.intro}</p>
        </header>
        <div className="space-y-4">
          {c.faqs.map((faq) => (
            <details key={faq.q} className="glass-card !p-0 overflow-hidden group">
              <summary className="px-6 py-4 font-hl font-bold text-slate-900 cursor-pointer list-none flex items-center justify-between hover:text-primary transition-colors">
                {faq.q}
                <span className="material-symbols-outlined text-slate-400 group-open:rotate-180 transition-transform text-[20px]">expand_more</span>
              </summary>
              <div className="px-6 pb-5 text-slate-600 text-sm leading-relaxed border-t border-slate-100 pt-4">
                {faq.a}
              </div>
            </details>
          ))}
        </div>
        <div className="mt-10 text-center">
          <a href={`/${locale}/contact`} className="text-primary font-bold hover:underline">{c.contact} →</a>
        </div>
      </div>
    </div>
  )
}
