import type { Metadata } from 'next';
import { buildAlternates } from '@/lib/hreflang';
import Breadcrumbs from '@/components/layout/Breadcrumbs';

type Props = { params: Promise<{ locale: string }> };

const CONTENT = {
  fr: {
    title: 'À propos de NovaDuel',
    description: 'NovaDuel est la plateforme de référence pour la comparaison avancée de joueurs de football et l\'analyse de performance basée sur l\'IA.',
    mission_heading: 'Notre Mission',
    mission: 'Fournir aux passionnés, recruteurs et analystes des outils de comparaison précis, objectifs et innovants pour décrypter les performances du football mondial.',
    values: [
      { label: 'Données Certifiées', text: 'Nous utilisons les flux officiels d\'API-Football pour garantir une précision maximale sur 9 ligues majeures.' },
      { label: 'Analyse IA', text: 'Nos analyses sont générées par Claude (Anthropic) et basées sur plus de 50 métriques par joueur.' },
      { label: 'Multilingue', text: 'La plateforme est disponible en français, anglais et espagnol pour une audience mondiale.' },
      { label: 'Mise à jour quotidienne', text: 'Les statistiques sont synchronisées chaque nuit pour refléter les performances les plus récentes.' },
    ],
  },
  en: {
    title: 'About NovaDuel',
    description: 'NovaDuel is the reference platform for advanced football player comparison and AI-based performance analysis.',
    mission_heading: 'Our Mission',
    mission: 'Provide fans, scouts and analysts with precise, objective and innovative comparison tools to decode world football performances.',
    values: [
      { label: 'Certified Data', text: 'We use official API-Football feeds to ensure maximum accuracy across 9 major leagues.' },
      { label: 'AI Analysis', text: 'Our analyses are generated by Claude (Anthropic) and based on over 50 metrics per player.' },
      { label: 'Multilingual', text: 'The platform is available in French, English and Spanish for a global audience.' },
      { label: 'Daily Updates', text: 'Statistics are synchronized every night to reflect the most recent performances.' },
    ],
  },
  es: {
    title: 'Acerca de NovaDuel',
    description: 'NovaDuel es la plataforma de referencia para la comparación avanzada de jugadores de fútbol y el análisis de rendimiento basado en IA.',
    mission_heading: 'Nuestra Misión',
    mission: 'Proporcionar a aficionados, reclutadores y analistas herramientas de comparación precisas, objetivas e innovadoras para descifrar el rendimiento del fútbol mundial.',
    values: [
      { label: 'Datos Certificados', text: 'Utilizamos los feeds oficiales de API-Football para garantizar la máxima precisión en 9 ligas principales.' },
      { label: 'Análisis IA', text: 'Nuestros análisis son generados por Claude (Anthropic) y se basan en más de 50 métricas por jugador.' },
      { label: 'Multilingüe', text: 'La plataforma está disponible en francés, inglés y español para una audiencia global.' },
      { label: 'Actualización diaria', text: 'Las estadísticas se sincronizan cada noche para reflejar los rendimientos más recientes.' },
    ],
  },
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  const c = CONTENT[locale as keyof typeof CONTENT] ?? CONTENT.en;
  return {
    title: `${c.title} | NovaDuel`,
    description: c.description,
    alternates: buildAlternates('/about', locale),
  };
}

export default async function AboutPage({ params }: Props) {
  const { locale } = await params;
  const c = CONTENT[locale as keyof typeof CONTENT] ?? CONTENT.en;

  return (
    <div className="bg-white min-h-screen">
      <div className="max-w-4xl mx-auto px-6 py-12 md:py-20">
        <Breadcrumbs
          items={[{ label: 'NovaDuel', href: '/' }, { label: c.title }]}
          locale={locale}
        />
        <header className="mt-8 mb-16">
          <h1 className="font-hl font-bold text-4xl md:text-5xl text-slate-900 tracking-tighter uppercase mb-6">
            {c.title}
          </h1>
          <p className="text-lg text-slate-600 leading-relaxed font-medium">{c.description}</p>
        </header>

        <section className="space-y-12">
          <div>
            <h2 className="text-xl font-bold text-slate-900 uppercase tracking-wider mb-4 border-l-4 border-primary pl-4">
              {c.mission_heading}
            </h2>
            <p className="text-slate-600 leading-relaxed">{c.mission}</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-8 border-t border-slate-100">
            {c.values.map((v) => (
              <div key={v.label} className="bg-slate-50 p-8 rounded-2xl border border-slate-100">
                <h3 className="font-hl font-black text-slate-900 mb-2 uppercase tracking-tight text-sm">{v.label}</h3>
                <p className="text-sm text-slate-500 leading-relaxed">{v.text}</p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
