import type { Metadata } from 'next';
import { buildAlternates } from '@/lib/hreflang';
import Breadcrumbs from '@/components/layout/Breadcrumbs';

type Props = { params: Promise<{ locale: string }> };

const CONTENT = {
  fr: {
    title: 'Méthodologie',
    description: 'Découvrez comment NovaDuel collecte, traite et présente les statistiques de football.',
    intro: 'Toutes les données affichées sur NovaDuel sont alimentées par API-Football, un fournisseur certifié de données sportives mondiales. Nous couvrons 9 championnats majeurs avec une mise à jour quotidienne des statistiques.',
    source_heading: 'Source des données',
    metrics_heading: 'Métriques clés',
    metrics_text: 'Chaque joueur est évalué selon quatre dimensions complémentaires, permettant une comparaison équitable quelle que soit la position ou la ligue.',
    metrics: [
      { label: 'Impact', value: 'Offensif & Créatif' },
      { label: 'Fiabilité', value: 'Défense & Duels' },
      { label: 'Influence', value: 'Passes & Progression' },
      { label: 'Régularité', value: 'Stabilité sur la saison' },
    ],
    ai_heading: 'Analyse IA',
    ai_text: "Les analyses comparatives sont générées par Claude (Anthropic), un modèle de langage avancé. Elles sont basées exclusivement sur les statistiques de la saison en cours et mises à jour périodiquement.",
  },
  en: {
    title: 'Methodology',
    description: 'Discover how NovaDuel collects, processes and presents football statistics.',
    intro: 'All data displayed on NovaDuel is powered by API-Football, a certified global sports data provider. We cover 9 major leagues with daily statistics updates.',
    source_heading: 'Data Source',
    metrics_heading: 'Key Metrics',
    metrics_text: 'Each player is evaluated across four complementary dimensions, enabling fair comparison regardless of position or league.',
    metrics: [
      { label: 'Impact', value: 'Offensive & Creative' },
      { label: 'Reliability', value: 'Defense & Duels' },
      { label: 'Influence', value: 'Passing & Progression' },
      { label: 'Consistency', value: 'Season Stability' },
    ],
    ai_heading: 'AI Analysis',
    ai_text: 'Comparative analyses are generated by Claude (Anthropic), an advanced language model. They are based exclusively on current season statistics and updated periodically.',
  },
  es: {
    title: 'Metodología',
    description: 'Descubre cómo NovaDuel recopila, procesa y presenta las estadísticas de fútbol.',
    intro: 'Todos los datos mostrados en NovaDuel son proporcionados por API-Football, un proveedor certificado de datos deportivos globales. Cubrimos 9 ligas principales con actualizaciones diarias de estadísticas.',
    source_heading: 'Fuente de datos',
    metrics_heading: 'Métricas clave',
    metrics_text: 'Cada jugador se evalúa en cuatro dimensiones complementarias, lo que permite una comparación justa independientemente de la posición o la liga.',
    metrics: [
      { label: 'Impacto', value: 'Ofensivo & Creativo' },
      { label: 'Fiabilidad', value: 'Defensa & Duelos' },
      { label: 'Influencia', value: 'Pases & Progresión' },
      { label: 'Regularidad', value: 'Estabilidad en la temporada' },
    ],
    ai_heading: 'Análisis IA',
    ai_text: 'Los análisis comparativos son generados por Claude (Anthropic), un modelo de lenguaje avanzado. Se basan exclusivamente en las estadísticas de la temporada actual y se actualizan periódicamente.',
  },
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  const c = CONTENT[locale as keyof typeof CONTENT] ?? CONTENT.en;
  return {
    title: `${c.title} | NovaDuel`,
    description: c.description,
    alternates: buildAlternates('/methodology', locale),
  };
}

export default async function MethodologyPage({ params }: Props) {
  const { locale } = await params;
  const c = CONTENT[locale as keyof typeof CONTENT] ?? CONTENT.en;

  return (
    <div className="bg-white min-h-screen">
      <div className="max-w-4xl mx-auto px-6 py-12 md:py-20">
        <Breadcrumbs
          items={[{ label: 'NovaDuel', href: '/' }, { label: c.title }]}
          locale={locale}
        />
        <header className="mt-8 mb-16">
          <h1 className="font-hl font-bold text-4xl md:text-5xl text-slate-900 tracking-tighter uppercase mb-6">
            {c.title}
          </h1>
          <p className="text-lg text-slate-600 leading-relaxed font-medium">{c.intro}</p>
        </header>

        <section className="space-y-12">
          <div>
            <h2 className="text-xl font-bold text-slate-900 uppercase tracking-wider mb-4 border-l-4 border-primary pl-4">
              {c.source_heading}
            </h2>
            <p className="text-slate-600">{c.intro}</p>
          </div>

          <div className="bg-slate-50 p-10 rounded-3xl border border-slate-100">
            <h2 className="text-xl font-bold text-slate-900 uppercase tracking-wider mb-4">
              {c.metrics_heading}
            </h2>
            <p className="text-slate-600 mb-8 leading-relaxed">{c.metrics_text}</p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {c.metrics.map((m) => (
                <div key={m.label} className="bg-white p-4 rounded-xl border border-slate-200">
                  <span className="text-[10px] font-black text-primary uppercase tracking-[0.2em]">{m.label}</span>
                  <p className="text-sm font-bold text-slate-800 mt-1">{m.value}</p>
                </div>
              ))}
            </div>
          </div>

          <div>
            <h2 className="text-xl font-bold text-slate-900 uppercase tracking-wider mb-4 border-l-4 border-primary pl-4">
              {c.ai_heading}
            </h2>
            <p className="text-slate-600 leading-relaxed">{c.ai_text}</p>
          </div>
        </section>
      </div>
    </div>
  );
}
